### ISSUE TITLE
guns disappear

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/vorp_banking#38] opened 2023-07-13 23:28 UTC
Weapons disappear when you take them into inventory from the bank safe deposit box

https://medal.tv/games/red-dead-2/clips/1jjtt2NdCz0OVe/d1337TOIW9S2?invite=cr-MSw0WTEsMTkzNjE2MDI1LA

**Comment by outsider31000** [comment] 2023-07-13 23:41
i just disabled it until the issue is found at least no one will be able store and lose the weapons

**Comment by systemNEO** [comment] 2023-07-14 00:20
Initial findings:

Reproduce the bug: Put a weapon in the bank inventory and then restart the server. After that, the weapon is still in the bank inventory. If you then put it back into the personal inventory, the error occurs.

The reason for the error is that weapons that are placed in the bank inventory no longer have a "charidentifier" in the "loadout" table and can no longer be loaded after the server restart, because no char assignment is possible. Until the server restart, these weapons are still in the cache, but not afterwards.

The weapon cache would therefore have to try to reload weapon IDs that it does not find in the cache from the database (onDemand). It is not recommended to load all weapons without char assignment at server start, that could lead to big performance problems.

I will try to create a simple fix.

**Comment by systemNEO** [comment] 2023-07-14 00:52
@outsider31000 See pull request https://github.com/VORPCORE/vorp_inventory-lua/pull/172

**Comment by outsider31000** [comment] 2023-07-14 00:54
i had this same issue months before your pull request , so it cant be from your edits

**Comment by systemNEO** [comment] 2023-07-14 00:55
Right, but this fixes it :) (I hope)

**Comment by outsider31000** [comment] 2023-07-14 01:00
but the issue is in here its not on the inventory

**Comment by outsider31000** [comment] 2023-07-14 01:04
if its removing the charidentifier then the issue is here

**Comment by outsider31000** [comment] 2023-07-14 01:07
@RobiZona 
have a look at this please

**Comment by systemNEO** [comment] 2023-07-14 02:41
Note: If you add the charidentifier then the related weapon is always in personal inventory. I think that was the reason why the charidentifier is nulled when the weapon is moved to the bank inventory.

**Comment by outsider31000** [comment] 2023-07-14 02:49
arent  you mistaking it with steamidentifier ?

**Comment by systemNEO** [comment] 2023-07-14 03:12
![image](https://github.com/VORPCORE/vorp_banking/assets/3120002/df8b0a05-3df5-45af-b3d5-3c37fc1ea673)

![image](https://github.com/VORPCORE/vorp_banking/assets/3120002/0edf78f4-4253-46dd-a4de-da6e1c1abfe7)

I mean the charidentifier - because it will be used to identify the weapons to load in `LoadDatabase()` if a player connects.

![image](https://github.com/VORPCORE/vorp_banking/assets/3120002/b1d316fd-5214-442a-9903-17480396afa7)

**Comment by outsider31000** [comment] 2023-07-14 03:14
but that is never null  only steamidentifier

**Comment by systemNEO** [comment] 2023-07-14 03:15
If you move a weapon from personal inventory to bank inventory than the charidentifier will be nulled currently. In older versions it was set to an empty string.

If you do not null the charidentifier after moving the weapon to bank inventory then the weapon remains in personal inventory, too. Because bank inventory do not change the `current_inv`. 

I am out for now - its late, gn8 ;)

**Comment by RobiZona** [comment] 2023-07-14 10:53
i'm trying to reproduce it

**Comment by RobiZona** [comment] 2023-07-14 11:01
@outsider31000
I did the procedure, put the weapon in the bank, restarted the server and got the weapon again and I had no problems, is it possible that changes have been made to "weapons" or "inventory"? because the weapon script when you don't have the weapon only deletes the identifier, the charidentifier remains so it is right that the check is done

**Comment by outsider31000** [comment] 2023-07-14 14:07
yes  the charidentifier cant be null , i had this issue before without the recent changes on the invnetory though i had to stop weapons from going inside the stash.
either way this will be fixed when using the API

**Comment by outsider31000** [comment] 2023-07-14 15:28
i was just adding the API but then I remember if I do it, all players  will loose all their items and weapons because this scripts uses its own logic to store items 
it would work for empty servers but not for full servers

**Comment by RobiZona** [comment] 2023-07-14 17:14
VorpInv.subWeapon(_source, weapId)

i used this for remove weapon

**Comment by outsider31000** [comment] 2023-07-14 17:15
the problem is weapon that dont go to inventory when player drag from bank

**Comment by RobiZona** [comment] 2023-07-14 17:17
VorpInv.giveWeapon(_source, weapId, 0)

is vorp API

**Comment by systemNEO** [comment] 2023-07-14 17:34
I told you so. But hey, so what? 🥇

**Comment by outsider31000** [comment] 2023-07-14 17:40
you told me what ?  why would there be an issue with the API  if it works with other scripts ?

**Comment by outsider31000** [comment] 2023-07-14 18:41
https://github.com/VORPCORE/vorp_inventory-lua

tested my self and weapons wont dissapear use the new version of this inventory

**Closed as completed by outsider31000** 2023-07-14 18:41 UTC

**Comment by systemNEO** [comment] 2023-07-14 19:26
Thanks, it works now. But API is now slow again. Great work! 🥇

**Comment by outsider31000** [comment] 2023-07-14 19:27
Better than not working...

**Comment by systemNEO** [comment] 2023-07-14 19:30
If you had understood and accepted the pull request, it would have worked and been fast. Nobody is perfect.
